import type { BookLine } from '../types';

/**
 * Named book lines the user can inspect and import. Each one is a complete
 * variation from move one; the import sheet lets the user take any prefix.
 */
export const BOOK_LINES: BookLine[] = [
  {
    id: 'bk_najdorf_pp',
    name: 'Najdorf — Poisoned Pawn',
    eco: 'B97',
    forColor: 'b',
    moves: 'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Bg5 e6 f4 Qb6 Qd2 Qxb2 Rb1 Qa3 e5 dxe5 fxe5 Nfd7 Ne4 h6 Bh4 Qxa2'.split(' '),
    summary: 'Black grabs the b2 pawn and defends. Sharp, heavily analysed, and still the critical test of 6.Bg5.',
    ideas: [
      'The queen on a3 is awkward but surprisingly hard to trap — Rb1 and Nb5 ideas must be met precisely.',
      'After e5 dxe5 fxe5, the knight retreats to d7 rather than d5; f6 breaks are the main freeing resource.',
      '...Qxa2 is the point: Black wins a second pawn and heads for an endgame where the extra material tells.',
    ],
    tags: ['sharp', 'theory-heavy', 'must-know'],
  },
  {
    id: 'bk_najdorf_english',
    name: 'Najdorf — English Attack',
    eco: 'B90',
    forColor: 'b',
    moves: 'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Be3 e5 Nb3 Be6 f3 Be7 Qd2 O-O O-O-O Nbd7 g4 b5 g5 b4 Ne2 Ne8'.split(' '),
    summary: 'Opposite-side castling and a mutual pawn storm. Black plays on the queenside; White throws the g- and h-pawns forward.',
    ideas: [
      'Count tempi, not pawns: whoever opens a file first usually wins the attack.',
      '...Ne8 sidesteps g5 and prepares ...Nb6-c4 or the ...f5 break.',
      'The d5 square is the permanent cost of ...e5 — Black must control it with ...Be6 and ...Nb6.',
    ],
    tags: ['opposite-castling', 'attacking'],
  },
  {
    id: 'bk_najdorf_opocensky',
    name: 'Najdorf — Opočenský (6.Be2)',
    eco: 'B92',
    forColor: 'b',
    moves: 'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Be2 e5 Nb3 Be7 O-O O-O Be3 Be6 Qd2 Nbd7 a4 Rc8'.split(' '),
    summary: 'The quiet main line. White builds slowly with a4 and Nd5 ideas; Black gets a sound, strategically rich game.',
    ideas: [
      'a4 stops ...b5, so Black switches to the c-file and ...Nb6 hitting a4 and c4.',
      'Trading the light-squared bishop on e6 usually helps White — keep it unless d5 becomes weak.',
      'A good practical choice when you want a Najdorf without memorising Poisoned Pawn theory.',
    ],
    tags: ['positional', 'low-theory'],
  },
  {
    id: 'bk_dragon_yugoslav',
    name: 'Sicilian Dragon — Yugoslav Attack',
    eco: 'B76',
    forColor: 'w',
    moves: 'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6 Be3 Bg7 f3 O-O Qd2 Nc6 Bc4 Bd7 O-O-O Rc8 Bb3 Ne5 h4 h5 Bg5 Rc5'.split(' '),
    summary: 'The classical race: White castles long and plays h4-h5 and Bh6; Black attacks down the c-file.',
    ideas: [
      'Bh6 trading dark-squared bishops is White’s main attacking idea — Black often answers with ...Rc5 and ...Qa8.',
      '...h5 stops h4-h5 at the cost of weakening g5 — Bg5 follows almost automatically.',
      'Sacrifices on c3 are a standing threat for Black in every line.',
    ],
    tags: ['sharp', 'opposite-castling'],
  },
  {
    id: 'bk_sveshnikov',
    name: 'Sicilian — Sveshnikov',
    eco: 'B33',
    forColor: 'b',
    moves: 'e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 Nf6 Nc3 e5 Ndb5 d6 Bg5 a6 Na3 b5 Bxf6 gxf6 Nd5 f5 Bd3 Be6 O-O Bxd5 exd5 Ne7'.split(' '),
    summary: 'Black accepts a backward d-pawn and a hole on d5 in return for the bishop pair and huge activity.',
    ideas: [
      '...f5-f4 and ...Bg7 give Black play on the kingside and along the long diagonal.',
      'White manoeuvres a knight to d5 or c4 and presses on the d6 pawn.',
      'Structurally unbalanced from move nine — good if you want to play for a win with Black.',
    ],
    tags: ['unbalanced', 'must-know'],
  },
  {
    id: 'bk_rossolimo',
    name: 'Sicilian — Rossolimo',
    eco: 'B30',
    forColor: 'w',
    moves: 'e4 c5 Nf3 Nc6 Bb5 g6 Bxc6 dxc6 d3 Bg7 h3 Nf6 Nc3 Nd7 Be3 e5'.split(' '),
    summary: 'A low-theory anti-Sicilian: trade on c6, keep the position closed, and play against the doubled pawns.',
    ideas: [
      'White wants Qd2, Bh6 and a knight to e3-d5 or c4.',
      'Black’s bishop pair is real compensation — do not let the position open carelessly.',
      'An excellent practical weapon if you do not want to learn the Open Sicilian.',
    ],
    tags: ['anti-sicilian', 'low-theory'],
  },
  {
    id: 'bk_ruy_closed',
    name: 'Ruy López — Closed, Chigorin',
    eco: 'C92',
    forColor: 'w',
    moves: 'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3 d6 c3 O-O h3 Na5 Bc2 c5 d4 Qc7'.split(' '),
    summary: 'The classical Spanish. White builds the big centre with c3 and d4; Black expands on the queenside and waits.',
    ideas: [
      'The knight manoeuvre Nb1-d2-f1-g3 is the standard regrouping.',
      'White must decide when to release the tension with d5 or dxe5.',
      'Slow, rich, and the most instructive structure in chess — worth learning even if you play something else.',
    ],
    tags: ['classical', 'positional'],
  },
  {
    id: 'bk_berlin',
    name: 'Ruy López — Berlin Endgame',
    eco: 'C67',
    forColor: 'b',
    moves: 'e4 e5 Nf3 Nc6 Bb5 Nf6 O-O Nxe4 d4 Nd6 Bxc6 dxc6 dxe5 Nf5 Qxd8+ Kxd8 h3 Ke8 Nc3 h5 Bf4 Be7 Rad1 Be6'.split(' '),
    summary: 'Queens come off by move eight. Black has the bishop pair and a damaged structure; White has a kingside majority.',
    ideas: [
      'The king on e8 is safe — do not waste time trying to castle by hand.',
      'White’s 4-vs-3 kingside majority is the long-term trump; Black’s bishops are the counterweight.',
      'The classic way to take the sting out of 1.e4 as Black.',
    ],
    tags: ['endgame', 'solid'],
  },
  {
    id: 'bk_italian',
    name: 'Italian — Giuoco Pianissimo',
    eco: 'C54',
    forColor: 'w',
    moves: 'e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d3 d6 O-O O-O Re1 a6 Bb3 Ba7 Nbd2 Ne7'.split(' '),
    summary: 'Slow build-up with d3 and c3, aiming for d4 at the right moment. The modern main line at every level.',
    ideas: [
      'Both sides manoeuvre knights to the kingside before committing the centre.',
      'Nbd2-f1-g3 and h3 are almost automatic for White.',
      'Very little forced theory — understanding beats memorisation here.',
    ],
    tags: ['positional', 'low-theory'],
  },
  {
    id: 'bk_winawer_pp',
    name: 'French — Winawer Poisoned Pawn',
    eco: 'C18',
    forColor: 'w',
    moves: 'e4 e6 d4 d5 Nc3 Bb4 e5 c5 a3 Bxc3+ bxc3 Ne7 Qg4 Qc7 Qxg7 Rg8 Qxh7 cxd4 Ne2 Nbc6 f4 Bd7'.split(' '),
    summary: 'White grabs g7 and h7 and gives back the centre. Enormously sharp and completely concrete.',
    ideas: [
      'White’s h-pawn is the long-term winner if the position survives the middlegame.',
      'Black’s counterplay comes down the g- and c-files against the shattered queenside.',
      'Know the move order exactly: transpositions here change the evaluation.',
    ],
    tags: ['sharp', 'theory-heavy'],
  },
  {
    id: 'bk_caro_classical',
    name: 'Caro-Kann — Classical',
    eco: 'B18',
    forColor: 'b',
    moves: 'e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Ng3 Bg6 h4 h6 Nf3 Nd7 h5 Bh7 Bd3 Bxd3 Qxd3 e6 Bf4 Ngf6 O-O-O Be7'.split(' '),
    summary: 'Black develops the problem bishop before ...e6 and accepts a small space deficit for a rock-solid structure.',
    ideas: [
      'Black’s structure is never bad — the game is about whether White’s space converts.',
      '...c5 at the right moment is the standard freeing break.',
      'Castling long for White signals a kingside pawn storm; Black often castles short anyway and races.',
    ],
    tags: ['solid', 'classical'],
  },
  {
    id: 'bk_nimzo_rubinstein',
    name: 'Nimzo-Indian — Rubinstein',
    eco: 'E46',
    forColor: 'b',
    moves: 'd4 Nf6 c4 e6 Nc3 Bb4 e3 O-O Bd3 d5 Nf3 c5 O-O dxc4 Bxc4 cxd4 exd4 b6 Bg5 Bb7'.split(' '),
    summary: 'The most flexible Nimzo. Black trades on c3 at the right moment and plays against the isolated or hanging pawns.',
    ideas: [
      'The whole opening is a fight over whether White gets a good version of an isolated d-pawn.',
      '...b6 and ...Bb7 pressure e4 and make d4-d5 hard to achieve.',
      'Keep the bishop on b4 until exchanging it wins something concrete.',
    ],
    tags: ['classical', 'positional'],
  },
  {
    id: 'bk_qgd_exchange',
    name: 'QGD — Exchange Variation',
    eco: 'D35',
    forColor: 'w',
    moves: 'd4 d5 c4 e6 Nc3 Nf6 cxd5 exd5 Bg5 c6 e3 Be7 Bd3 Nbd7 Qc2 O-O Nge2 Re8 O-O Nf8'.split(' '),
    summary: 'The minority attack: White plays b4-b5 to leave Black with a weak c-pawn.',
    ideas: [
      'b4-b5 and the resulting backward c6 pawn is the plan — everything else serves it.',
      'Nge2 rather than Nf3 keeps the f-pawn free for a central or kingside advance.',
      'Black counters with ...Ne4 and play on the kingside, or ...a5 stopping b4 outright.',
    ],
    tags: ['positional', 'plan-driven'],
  },
  {
    id: 'bk_semislav_botvinnik',
    name: 'Semi-Slav — Botvinnik Variation',
    eco: 'D44',
    forColor: 'b',
    moves: 'd4 d5 c4 e6 Nf3 Nf6 Nc3 c6 Bg5 dxc4 e4 b5 e5 h6 Bh4 g5 Nxg5 hxg5 Bxg5 Nbd7 exf6 Bb7 g3 c5'.split(' '),
    summary: 'A piece sacrifice by move eleven that has been analysed to move thirty. The sharpest line in the Queen’s Gambit.',
    ideas: [
      'Black’s extra pawns on the queenside and the b7 bishop are the compensation for the piece.',
      'Every move is forced for a long stretch — this is memorisation, not understanding.',
      'Only play it if you will actually maintain the theory.',
    ],
    tags: ['sharp', 'theory-heavy'],
  },
  {
    id: 'bk_kid_mardelplata',
    name: "King's Indian — Mar del Plata",
    eco: 'E97',
    forColor: 'b',
    moves: 'd4 Nf6 c4 g6 Nc3 Bg7 e4 d6 Nf3 O-O Be2 e5 O-O Nc6 d5 Ne7 Ne1 Nd7 Nd3 f5 Bd2 Nf6 f3 f4'.split(' '),
    summary: 'The purest race in chess: White attacks on the queenside with c4-c5, Black on the kingside with ...f5-f4 and ...g5.',
    ideas: [
      'Do not count pawns — count moves to the enemy king.',
      '...Nf6-h5, ...g5, ...Rf7-g7 is the standard attacking formation.',
      'If White breaks through on c7 first, Black is simply lost; commit fully.',
    ],
    tags: ['sharp', 'attacking'],
  },
  {
    id: 'bk_grunfeld_exchange',
    name: 'Grünfeld — Exchange Variation',
    eco: 'D85',
    forColor: 'w',
    moves: 'd4 Nf6 c4 g6 Nc3 d5 cxd5 Nxd5 e4 Nxc3 bxc3 Bg7 Nf3 c5 Rb1 O-O Be2 cxd4 cxd4 Qa5+ Bd2 Qxa2'.split(' '),
    summary: 'White builds an imposing centre; Black attacks it immediately with ...c5, ...Bg7 and pressure on d4.',
    ideas: [
      'The big centre is a target, not an asset, until White proves otherwise.',
      'Rb1 sidesteps the ...Qa5 pin and prepares to push the d-pawn.',
      '...Qxa2 wins a pawn but leaves the queen offside — White plays for the initiative with O-O and Bg5.',
    ],
    tags: ['sharp', 'classical'],
  },
  {
    id: 'bk_benko',
    name: 'Benko Gambit',
    eco: 'A57',
    forColor: 'b',
    moves: 'd4 Nf6 c4 c5 d5 b5 cxb5 a6 bxa6 Bxa6 Nc3 d6 e4 Bxf1 Kxf1 g6 g3 Bg7 Kg2 O-O'.split(' '),
    summary: 'A pawn for permanent queenside pressure. The compensation is positional and lasts into the endgame.',
    ideas: [
      'The a- and b-files are Black’s entire game — double rooks and never trade them off cheaply.',
      'White’s king walks to g2 by hand; Black gains time but no material back.',
      'One of the few gambits where trading queens does not kill the compensation.',
    ],
    tags: ['gambit', 'positional'],
  },
];
